### ISSUE TITLE
recent type changes of models smdx_00211 to smdx_00214

### ISSUE THREAD

**Issue by ghost** [sunspec/models#11]
We've noticed that there were some type changes in models smdx_00211, smdx_00212, smdx_00213 and smdx_00214 in commit 3b753155f0af1f57db7f1e98d0c9447a805b1b13 on Feb 4th 2016 and have some questions regarding the changes.
- Is updating to the new models madatory?
- If so, how can we deal with non-updateable devices already deployed in the field? E.g. say we have third-party meter devices in the field that only support the acc32 types and which cannot be updated. If we now update to the new version that supports only float32 types, is there any support to distiguish such legacy devices from "new" ones?
- Why was there an update to already approved models? 
- Why was the model version not incremented?
- How likley is it that there are further changes to approved models? 

Best regards, Martin Preinfalk

**Comment by bobfox** [comment]
Martin,

The changes were made to what was assessed as an error. We did not know anyone was using them in a production setting at this time. I would like to understand your situation more completely so we can make the appropriate resolution. Can you email me at bob@sunspec.org with your contact information?

Bob Fox
