### ISSUE TITLE
Model 705 VRef Points at Wrong Scope Level?

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#123]
The **Volt-Var VRef** points (`VRef`, `VRefAuto`, `VRefAutoEna`, `VRefTms`) are defined as curve points. Shouldn't they be defined as common points? Are there use cases where each curve would require a different `VRef`? How could they have a different `VRefAuto`? Would any inverter support multiple `VRef` values? 

**Suggestion:** Move the **VRef** points from the curve to the common area. 

**Also:** Should `VRefTms` be called `VRefAutoTms`?

**Comment by bobfox** [comment]
No change. This mechanism match IEEE 2030.5 implementation.
