### ISSUE TITLE
DID 705 VRef Auto Response Time Point Name and Description Change

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#124]
The point name is currently **VRefTms**. Because this is a response time, I propose changing it to **VRefAutoRspTms**, which will also make it consistent with the curve response time point **RspTms**. 

Also, the description should read: 

> Autonomous VRef response time.

**Comment by shelcrow** [comment]
VRefTms is not an open loop response time, so Rsp doesn't seem quite right. We are proposing it be renamed to VRefAutoTms.

**Comment by jsbosch** [comment]
Agreed.
