### ISSUE TITLE
Inconsistent ordering of reversion control and related timers

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#126]
For example, in 704 we have this order, with the control first, followed by timer setpoint and then remaining time:
1. VarSetRvrtEna
2. VarSetRvrtTms
3. VarSetRvrtRem

But in 705 (and the other non-trip curve controls), we have this order, which places the control (reversion curve number) after its related timer settings:
1. RvrtTms
2. RvrtRem
3. RvrtCrv

To me, the ordering in 704 makes the most sense, but I'd at least like to see consistent ordering unless there's a strong reason for the inconsistency.

**Comment by shelcrow** [comment]
On further inspection, it seems like RvrtEna is not necessary and not consistent with the reversion state machine. We propose removing the RvrtEna points in 704.

**Comment by jsbosch** [comment]
That would work.

**Comment by shelcrow** [comment]
On second look, RvrtEna is really the enable setting on reversion, not whether reversion was enabled, so we will not be removing it
