### ISSUE TITLE
DID 712 Curve Point Names

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#128]
The curve points for the Watt-Var model are named W and Var. This is not consistent with 1547-2018 in that the spec uses P and Q (and their negatives). (The control name is also different, being Active Power-Reactive Power, but that's not as succinct as Watt-Var.)

![image](https://user-images.githubusercontent.com/12519613/92797927-5fa43700-f367-11ea-9650-0976af2b58c2.png)

**Comment by shelcrow** [comment]
SunSpec models use the same abbreviations for the same concepts throughout all the models. W represents active power, and Var represents reactive power. That's the rationale for the naming here.

**Comment by jsbosch** [comment]
But the 700 level models are intended to follow 1547, no? By keeping the W and Var names, not only is the model out of step with the spec, but it also requires a somewhat-clumsy non-intuitive mapping of SunSpec to 1547. For example, if we follow the normal order of evaluating a graph from left to right, we get this mapping:


P1 > W4
P2 > W5
P3 > W6
P1n > W3
P2n > W2
P3n > W1
Q_1 > Var4
Q_2 > Var5
Q_3 > Var6
Q1n > Var3
Q2n > Var2
Q3n > Var1

That's nasty and non-intuitive, and really falls on IEEE for having this one curve fan out from the vertical axis rather than go in the natural order of left-to-right.

**Comment by bobfox** [comment]
Curve points are named in uniform way.
