### ISSUE TITLE
RspTms missing scale factor for DID 705, 706, 712

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#130]
IEEE 1547-2018 sets a range requirement of 0.5 to 60s. IEEE 2030.5 specified resolution in 1/100 of a second. SunSpec models provide only integer resolution. 

**Proposed Solution**
Add a RspTms_SF to the three models.

**Better Solution**
Note in the units field that the value is specified in milliseconds, which is what the name seems to indicate.

**IEEE 1547-2018:**
![image](https://user-images.githubusercontent.com/12519613/92966536-95f7ba00-f42c-11ea-8af2-c07c77fc2f19.png)

**IEEE 2030.5: (from sep.xsd)**

```
<xs:element name="openLoopTms" minOccurs="0" maxOccurs="1" type="UInt16">
            <xs:annotation>
              <xs:documentation>
                     Open loop response time, the time to ramp up to 90% of the new target in 
                     response to the change in voltage, in hundredths of a second. Resolution is 
                     1/100 sec. A value of 0 is used to mean no limit. When not present, the device 
                     SHOULD follow its default behavior.
             </xs:documentation>
            </xs:annotation>
          </xs:element>
```

**Comment by shelcrow** [comment]
Which units field is value specified in milliseconds?

**Comment by jsbosch** [comment]
None are. That's a suggestion. 

The naming convention "Tms" indicates to me that the field is "Time in milliseconds". Maybe something else was intended. 

One issue with using milliseconds: You limit the period to about 65.5 seconds, which may be too short for some applications.

**Comment by bobfox** [comment]
In this case the 'Tm' is the abbreviation used for time in SunSpec information models so Tms is in seconds. All the models with RspTms are being updated to have a scale factor just in case sub-second accuracy is required.

**Comment by jsbosch** [comment]
Ah, didn't know that was the naming convention (though I suspected it could be). IEEE 1547 requires fraction of a second resolution, so adding the SF is a good step. Thanks.

**Comment by jsbosch** [comment]
One potential issue: 1547-2018 and HECO have trip requirements with ranges fro 160ms to 1000s. I think we need to make trip time registers 32 bit with a scale factor of -2 for hundredths of a second resolution.

![image](https://user-images.githubusercontent.com/12519613/93394224-b955a700-f828-11ea-93e9-ffb0a0fc8fa4.png)
