### ISSUE TITLE
Active Power Setpoints in DID704 - Wrong Data Type?

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#135]
The active power setpoints are specified as int32. Shouldn't they be int16? 
- WSet
- WSetRvrt
- WSetPct 
- WSetPctRvrt

**Comment by jsbosch** [comment]
Actually, let's extend that to the other setpoints in 704 as well. Do we really need 32 bits for VarSet, etc? Doesn't seem like we do.

**Comment by bobfox** [comment]
Resolved.
