### ISSUE TITLE
Extend AC Measurement (DID 701) Hz to 32 Bit

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#138]
We would like the option to express grid frequency in 0.001 Hz resolution, which would need to use 32 bits to read values above 65.534 Hz (65535 would mark it unimplemented). Changing this point to 32 bits would also add consistency with the other Hz points, which are also 32 bits.

**Comment by shelcrow** [comment]
In commit 5c80217c8d52408f93f67154f35b5a790837dbad 'Hz' point type was changed to 'uint32' in models 709, 710, 711
