### ISSUE TITLE
Unit/Data Type Consistency?

### ISSUE THREAD

**Issue by shelcrow** [sunspec/models#141]
Should points with the same units use the same data type throughout all the 7xx models?

**Comment by jsbosch** [comment]
As long as the data type can hold the largest value needed for the units, then it can't hurt, other than maybe taking up a little more space and bandwidth. For example, _ESHzHi_ is specified in IEEE 1547-2018 as having 0.1Hz resolution, while grid frequency measurements may need to be made in 0.001Hz resolution. Both are measured in Hz. In this case, the two data types don't need to be the same, but they can be as long as the type can accommodate both resolutions (would need to be 32bit), and implementations can simply ignore the extra resolution in _ESHzHi_ if not needed.

**Comment by shelcrow** [comment]
The list of updated types and units:
- Models 709, 710, 711: change 'Hz' point type to 'uint32'
- Models 701, 704: 'Pct' type Points to 'uint16'
- Models 705, 706, 711, 703: 'Secs' type Points to 'uint32'
- Model 704: '%Max/Sec' type Points to 'uint16'
- Models 712, 705: 'VarPct' type Points to 'uint16'
- Model 706: 'DeptRef' type Points to 'uint16'
- Model 712: 'WMaxPct' type Points to 'uint16'
