### ISSUE TITLE
Model 702 - Update Vnom point name to VNom

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#144]
Update Vnom point name to VNom for consistency.

**Comment by jsbosch** [comment]
I wonder if it's more accurate to leave it as-is, because "nom" is basically a subscript to describe which voltage V refers to.

**Comment by bobfox** [comment]
In the same model, there is VNomRtg. The general rule for SunSpec point
names is that each name segment starts with a cap, so it seems VNom is more
consistent with that usage and the other existing point in the model.
