### ISSUE TITLE
Model 701 - Update PF type to uint16

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#146]
Update measured PF to be unsigned to treat the reading the same as most meters. The sign of reactive power indicates the quadrant in this case.

**Comment by jsbosch** [comment]
May want to update the notes:

```
"name": "PF",
"notes": "The power factor as computed by xxx. [Should it be signed?]",
"sf": "PF_SF",
```

**Comment by jsbosch** [comment]
Shouldn't PF be signed? In DID 704, the sign is implied by the Ext point. There's no corresponding point for DID 701 PF.
