### ISSUE TITLE
Model 704 - Add var ramp rate point

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#150]
Add a point to support specification of reactive power ramping.

**Comment by jmmgenerac** [comment]
While we're in here adding the VarRamp point, we may want to consider two questions on the active power ramp rate AGra: 

- Can AGra be renamed to WRamp?
- Do we really need 32 bits for this field whose units are percentage?

**Comment by shelcrow** [comment]
We changed point 'RGra' to 'WRmp', and changed the type to 'uint16.'
