### ISSUE TITLE
Negative percent

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#154]

**Comment by bobfox** [comment]
Percent can be negative for controls. Review all points with percent units and update to signed type where appropriate.

**Comment by shelcrow** [comment]
Type changed to int16 for Points:
(704) 'WSetPct', 'WSetPctRvrt', 'VarSetPct', 'VarSetPctRvrt';
(705) 'Var';
(706) 'W';
(712) 'W', 'Var'
