### ISSUE TITLE
Multiple Models: ActPt naming consistency?

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#160]
Points specifying the number of items generally start with 'N': NPt, NCrv. 

ActPt specifies a number of active points but does not start with 'N', which to me is inconsistent. Is there a reason for the inconsistency?

**Comment by bobfox** [comment]
There is no specific reason. In the curve models the N* points are limits while the ActPt point is the current number of active points.  In this case, Act is an alternate version of N that also indicates active. We try to keep the point name as short a possible.
