### ISSUE TITLE
the type "count" used in model 160 is not defined anywhere

### ISSUE THREAD

**Issue by jonseymour** [sunspec/models#17]
5 models (160, 401, 402, 403, 404) use a type called 'count' which is not explicitly defined by the information model.

Is this type equivalent to uint16 or to int16? If not, in what ways does it different from these other types?

**Comment by silvia2019** [comment]
Count type is equivalent to uint16 - Updating model specification.

**Comment by cfstras** [comment]
@silvia2019: what's the value for "not implemented"? Is it 0x0000 as the other acc types, or 0xffff, as in uint16?

**Comment by silvia2019** [comment]
@cfstras: it's 0xffff as uint16
