### ISSUE TITLE
Model 804 has an alignment error

### ISSUE THREAD

**Issue by jonseymour** [sunspec/models#18]
As currently declared, EvtVnd2 and SetEna overlap. Either ExtVnd2 should be re-declared as a single 16 bit register, or all subsequent points should have their offsets adjusted so that adjacent points do not overlap.

```
<point id="EvtVnd2" offset="28" type="bitfield32" />
<point id="SetEna" offset="29" access="rw" type="enum16" />
```

**Comment by silvia2019** [comment]
Model 804 was updated after this comment.  It no longer has an alignment issue.
