### ISSUE TITLE
Make curve indices 0-based?

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#188]
Now that enums are all zero-based, why not change the curve indexes to 0-based as well? Then "Curve 0" holds the current settings, curve 1 starts the settable curves. Because curve 0 is read only, the 0 even seems to me to reinforce it's "not a writable curve" status. This would also be more consistent with the other data types being 0-based. 

Thoughts?

**Comment by bobfox** [comment]
After our discussion, we will leave the curve indices 1-based.
