### ISSUE TITLE
description property name in json models does not match schema

### ISSUE THREAD

**Issue by wz2b** [sunspec/models#197]
The schema says that a point has a property "description" but in all the models it shows up as "desc.' 

Which one of these is correct?

https://github.com/sunspec/models/blob/c1c980c48c55ecd3b037588d3ba7c8c4e5edafff/json/schema.json#L130
https://github.com/sunspec/models/blob/c1c980c48c55ecd3b037588d3ba7c8c4e5edafff/json/model_1.json#L8

**Comment by shelcrow** [comment]
'desc' is the right one, and we will update the schema.

**Comment by wz2b** [comment]
That's fine, either way is fine with me... but 'description' is used in other places so it's a bit inconsistent.  Will close this ticket when you commit the change.
