### ISSUE TITLE
ID, Length, and Enable points should have consistent labels across models

### ISSUE THREAD

**Issue by shelcrow** [sunspec/models#199]
E.g.:

1:
    ID - Model ID
    L - Model Length
    Ena - Module Enable

707:
    ID - DER Trip LV Model ID
    L - DER Trip LV Model Length
    Ena - DER Trip LV Module Enable

We are proposing that ID and L labels should be "Model ID" and "Model Length", while Ena labels should be qualified with the model name, like: "DER Trip LV Module Enable"

**Comment by wz2b** [comment]
I second this - I am generating code based on all these fields, and consistency is helpful.
