### ISSUE TITLE
Model 803 missing V_SF datapoint

### ISSUE THREAD

**Issue by mbe-lb** [sunspec/models#20]
These Points refer to V_SF but it is not defined in this model.

15       point id="StrVMax" offset="9" type="uint16" sf="V_SF" units="V" /> 
16       point id="StrVMaxStr" offset="10" type="uint16" /> 
17       point id="StrVMin" offset="11" type="uint16" sf="V_SF" units="V" /> 
18       point id="StrVMinStr" offset="12" type="uint16" /> 
19       point id="StrVAvg" offset="13" type="uint16" sf="V_SF" units="V" /> 

Suggestion: one could replace
point id="Pad1" offset="24" type="pad" mandatory="true"
for this.

**Comment by silvia2019** [comment]
This model was updated after the issue was raised.
