### ISSUE TITLE
AdptCrvReq value on curve adoption completion

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#203]
(I'm going to leave this as-is for now. I just found out that the tester was using the old Dashboard and pysunspec. So, I'm not sure if this is a valid issue, though I would really like to know if there is specific behavior expected as described. Thanks!)

We're running into an issue with the AdptCrvReq value after requesting a curve using Dashboard or pysunspec2. Seems that the point should maybe be set to 1 on successful curve adoption or 0 on error. Leaving the value unchanged causes the Dashboard and pysunspec library to not write even if other curve values change because they will only write if the field is marked "dirty". I can't find the behavior defined or described in the specifications. 

**Example**
1. Update Crv2 values. 
2. Set AdptCrvReq = 2. Crv1 will reflect Crv2.
3. Update Crv2 values again.
4. Set AdptCrvReq = 2. Crv1 will NOT reflect Crv2 because both the Dashboard and the pysunspec library will not mark AdptCrvReq as "dirty" and so will not send the request. (This does not happen in our in-house tool because it does not check that the data changed, only that the write was requested.)

**Comment by bobfox** [comment]
I am not seeing this behavior in the SVP Dashboard. When I perform the steps you outline, the request is sent again. This was a bad "feature" in the original Dashboard. Which version of the Dashboard are you using?

**Comment by jsbosch** [comment]
Old Dashboard (which I learned after creating the ticket). I left the ticket open to see if we want to define the behavior of the AdptCrvReq on success or error.
