### ISSUE TITLE
Model 702 - Should absorption ratings and setting be a negative number 

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#204]
Currently VarMaxAbsRtg is unsigned. Absorption is in the name but it seems more intuitive for the setting to be negative. The var ratings in quadrants 2 and 3 in model 120 are signed and expected to be negative.

**Comment by FW22** [comment]
At SMA we treat all parameters related to reactive power absorption as signed and use negative values.  Even if this might be confusing because of the  term “max”.

**Comment by FW22** [comment]
Reactive power absorption applies to quadrants 3 and 4 (not 2 and 3 as you stated). And my understanding of IEEE1547 is, that this standard covers active power feed-in quadrants 1 and 4 only.
As such, the 702-VarMaxAbsRtg is the equivalent to 120-VArMaxQ4 and 702-VarMaxInjRtg is the equivalent to 120-VArMaxQ1.
There is no 702-equivalent for 120-VArMaxQ2 ans 120-VArMaxQ3.
Please correct me if I missed something...

**Comment by bobfox** [comment]
You are right of course. I was thinking about active power relative to the quadrants for some reason. I meant 1 and 4 for reactive power.

We need to change the VarMaxAbsRtg and VarMaxAbs from uint16 to int16.

**Comment by bobfox** [comment]
After discussion in the SunSpec Modbus workgroup today, the consensus is to leave the VarMaxAbsRtg and VarMaxAbs unsigned.  The following factors led to favoring this approach:
- Leaving it unsigned keeps the type and range consistent with the var injection rating.
- The direction of flow is contained in name.
- 1547-2018 does not seem to indicate that the rating should be expressed as a negative number.
- It is also the approach taken with the charge ratings.
