### ISSUE TITLE
Clarify behaviour of Ena-Register in model 704 (AC Controls) compared to model 123 (Immediate controls)

### ISSUE THREAD

**Issue by FW22** [sunspec/models#213]
Hello @bobfox,

model 704 (AC Controls) contains Ena-registers for every type of setpoint:

- Power Factor Enable (W Inj)
- Power Factor Reversion Enable (WInj)
- Power Factor Enable (W Abs)
- Power Factor Reversion Enable (W Abs)
- Limit Max Power Pct Enable
- Reversion Limit Max Power Pct Enable
- Set Active Power Enable
- Reversion Active Power Enable
- Set Reactive Power Enable
- Reversion Reactive Power Enable

The "old" model 123 (immediate controls, which should be replaced by model 704) contained a handfull of such enable registers, too:

- WMaxLimEna
- OutPFSet_Ena
- VArPct_Ena

...and the associated specification contained a detailed description of the expected behaviour:
![image](https://user-images.githubusercontent.com/56593428/115258283-2586e900-a131-11eb-9933-d269b09833f2.png)

Unfortunately, I didn't find any details about model 704 regarding the enable registers. The only section that talks about enable is the curve management section. But model 704 is not about curves.

Do you expect them to behave similar to those in model 123? Each time a control value is changed, the associated enable register must be written with ENABLE?

Thank you for clarification!
Best regards
Ferdinand

**Comment by bobfox** [comment]
Model 704 does not have any requirement to write to the enable (Ena) register after changing the value for an enabled function. The enable register indicates whether the control is active. Any value change for an enabled function should take effect immediately.

Updating the enable point does have an effect on the reversion timer logic as described in the reversion timer section of the DER information model specification.

**Comment by FW22** [comment]
Ok, thanks for clarification!

**Comment by FW22** [comment]
hi @bobfox,
another question to clarify the behaviour of ENA-registers in model 123:
"Each time a control value is changed, the associated enable register must be written with the ENABLED value (1)."
What does that mean for the controlled device?
Shall it buffer the other registers of the control function (e.g. WMaxLimPct, WMinTms, RvrtTms and RmpTms) and apply them only if and when the associated enable register is written with the ENABLED value?
Or shall it apply all registers immedeately and use the ENABLED trigger to reset the reversion timer only?
Best regards
Ferdinand

**Comment by bobfox** [comment]
The Ena requirements changed for the 1xx as they were being used. They were introduced and then started to be implemented several years later. The synchronization complications for the curve-based controls drove the need to base adoption of  the curve settings based on rewriting Ena when the settings were complete. The controls in 123 were documented the same way for consistency but some manufacturers had already implemented them where the change takes effect without rewriting Ena. Based on that, it is currently the choice of the manufacturer for model 123. One of the objectives of the 7xx models is to provide a better synchronization mechanism so all implementations can be consistent.
