### ISSUE TITLE
Model 701 InvSt - Shouldn't it have a "RUNNING" state?

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#218]
When the inverter is on (**St** == **ON**), shouldn't **InvSt** reflect the status of the inverter under normal operating conditions? Seems we need an additional state such as **RUNNING** or **OPERATING**. **STANDBY** seems redundant with **SLEEPING**, so can we perhaps repurpose that slot?

**Comment by bobfox** [comment]
Historically, the MPPT state has been intended to be the normal running state but this PV centric. I think we should change MPPT to RUNNING. Any comments?

**Comment by jsbosch** [comment]
I agree with the change.

**Comment by FW22** [comment]
I also agree... but isnt it too late for a breaking change? The standard is published and industry is already implementing Off, Sleeping, Starting, MPPT, Throttled, ShuttingDown, Fault, Standby.
If you change MPPT to Running, you should make very clear that for PV inverters, this means MPPT and that they should indicate Throttled if the are running curtailed by some external or internal power limit.

**Comment by jsbosch** [comment]
I don't believe this is a breaking change. The label is not sent as a value, so implementations can really call it whatever they want.

**Comment by bobfox** [comment]
I agree, it is not a breaking change at the Modbus level. It is a breaking change at the model definition level. We have discussed internally and will bring it to the workgroup next week for a decision. I recommend we make the correction. This one seems particularly important to fully support storage inverters. I also think MPPT was just a poor choice to begin with.

**Comment by FW22** [comment]
If you are going to have a discussion on this, please consider the other states as well:
The THROTTLED state is also PV specific and does not apply to battery inverters.
SLEEPING sounds like what the PV inverter does at night. STANDBY would be better.

**Comment by bobfox** [comment]
The MPPT enumeration will be changed to RUNNING. The other enumerations remain the same as there is little support for additional changes.
