### ISSUE TITLE
DID 701 PF - Should be Signed?

### ISSUE THREAD

**Issue by jsbosch** [sunspec/models#219]
Shouldn't PF be signed? In DID 704, the sign is implied by the Ext point. There's no corresponding point for DID 701 PF.

(Originally changed to unsigned in #146.)

**Comment by bobfox** [comment]
Yes, I think you are probably right, PF in 701 should be signed. The sign is the mathematical result of active power/apparent power so PF is negative if active power is negative. The PF holds no information about excitation.

**Comment by FW22** [comment]
This would be a breaking change. How should a machine know which version of the standard another machine is based on? The models have been published and approved. I’m afraid its to late for a change.

**Comment by bobfox** [comment]
Technically, it is too late. It has only been a couple of weeks and nothing has been tested or certified yet, however, so if we felt it was really important, a case could be made to fix it. Once any official testing or certification is performed, it will be too late.

**Comment by jsbosch** [comment]
Is there a decision about this, or should we discuss it in the next workgroup meeting?

**Comment by bobfox** [comment]
We have discussed it internally, and will bring it to the workgroup meeting next week for a decision. My recommendation is to make the correction.

**Comment by jsbosch** [comment]
Thanks, I agree.

**Comment by bobfox** [comment]
We will update all power factors in model 701 to be signed. The sign of the model 701 power factor should be the sign of active power. All the models are generator reference so active power is positive for generation and negative for absorption.

The power factor value settings in model 704 will remain unsigned with the excitation indicated the excitation field.

**Comment by FW22** [comment]
@bobfox: the sign of the power factor must be the sign of **reactive** power. Not active power.

**Comment by bobfox** [comment]
Power factor = active power/apparent power. In model 701, PF = W/VA. If W is negative, PF is negative.

**Comment by FW22** [comment]
@bobfox : I had to think about that for a while. As you know there are several different sign conventions for the power factor:

1. EEI - the sign is related to the impedance (capacitive / inductive)
2. IEC - the sign is related to the active power flow
3. Excitation-signed - the sign is related to the reactive power (overexcited / underexcited)

For power factor setpoints in model 704, no sign is used, but the excitation is set by a separte register (PFExt).

The major use case for the power-factor registers in model 701 is, to compare them with the power factor setpoints.
To make this comparison as easy as possible, both models should follow the same conventions.

How would you make this comparison with the current approach?

**Comment by bobfox** [comment]
Sorry, I should have put more in my last comment.

The rational here is that there are two contexts for DER power factor values: measurements and settings.

When power factor is reported as part of monitoring data, it is a signed value where the sign of power factor is the sign of active power used to compute the power factor. The power factor measurement does not indicate excitation. To determine excitation in monitoring data, the reactive power value needs to be examined. The approach here to be consistent with the way measurement devices such as meters represent power factor. In IEEE 2030.5, for example, reporting of power factor is part of the metering package. not the DER package. The metering package has no concept of excitation. I think it is the same with independent metering devices.

A power factor setting in this context consists of a power factor value and an excitation. The power factor setting value is unsigned. The constant power factor setting in 1547-2018 is the power factor value and excitation to be used during generation. It may be desirable to apply a different power factor value and excitation when active power is being absorbed. The standard does not specify a power factor setting when absorbing active power. The three standard protocols specified in the standard have the ability to specify a separate constant power factor setting when absorbing active power but its support is not required by 1547-2018. It is intended to utilize the additional setting in a future version of the standard.

It seems, in the case, being consistent with other measurement devices for measurement data coming from model 701 is more desirable than making a comparison easier with a power factor settings value.
