### ISSUE TITLE
Question - Where are the SID, ID, L values in models

### ISSUE THREAD

**Issue by jeffdeville** [sunspec/models#22]
I'm working with a Fronius inverter, and while comparing their register map to yours, I've found some inconsistencies.  Here's their doc:
http://take.ms/7Ikq3

On Page 89, their common model includes an SID, ID, and L property that isn't reflected in smdx_00001.xml.  Also, their model length is 65, while yours is 66 (this may be just the 'Pad' value)

They always include an ID, L property in each model, whereas in your docs, it's always missing.

My understanding is that their products are sunspec certified though, so I'm assuming that your docs and theirs ARE saying the same thing, but that I'm misunderstanding something.  

I don't suppose someone could enlighten me?  

# Motivation for Sunspec

I'm working on this OSS elixir client (master).  
https://github.com/jeffdeville/ex_sunspec

Now that I've found this project, I'm hoping to be able to create clients as easily as:

```elixir
defmodule Fronius.Inverter do
  use ExSunspec, start: 40_000, models: [1, 101, 120, 123]
end
```

This is working, except that my memory addresses are incorrect!

**Comment by connium** [comment]
**model length**
SunSpec says that each model must start at an even register address. This means that the models must contain an even number of registers. According to the specification the length of 66 registers as it is given in `smdx_00001.xml` is correct. If you take at look at the registers defined there you will see, that at register 65 there is a register with length 1 and type `pad`. This means that it is a filling register and does not contain any data. Unfortunately some vendors do not include this padding register (like your Fronius device).
So the correct length would be 66, but you won't loose any information if it is given with a length of 65.

**SID**
The SID is not part of any model. Instead it is an indicator that this is a SunSpec compatible device and marks the starting point of the models. That's the reason why it is not included in the common model.
Usually the SID is located at register 40001 (equals to address 40000). This seems to be the case for the Fronius inverter as well.

**ID, L**
The `smdx` files describe the models. The **ID** and **L**ength of the models actually are not part of the models but form a **model header**. The model header is generic and contains the ID of the subsequent model and the length of the model which is especially important for models with a variable length. From the model header you can determine the start of the next model respective the model header of the next model.
So the layout is as follows:

|Register|Value|
|---|---|
|40001-40002|SID|
| | |
|40003|ID (of the common model)|
|40004|Length (of the common model)|
|40005-40069|the common model|
| | |
|40070|ID (of the next model - in your case maybe the single phase inverter model)|
|40071|Lenght|
| | |
|40072-40xxx|the next model|

**Comment by jeffdeville** [comment]
Thank you @connium!  That should be enough to get me moving again!

**Comment by jeffdeville** [comment]
Thanks again @connium. It *looks* like the fronius docs are wrong.  It looks like when they say offset 1, what they really mean is 0.  I'll mention it to them.

**Comment by jeffdeville** [comment]
@connium - Sorry, one more question. It turns out the struggle was indeed related to the model length of 65 vs 66. (I calculate the starting point for the next model using the 'length' value).  The Fronius team tells me that the spec was initially length 65, and was changed after adoption. I've created a flag to handle this case, but I'd like to know if there are any other oddities like this I should be aware of?
Thanks!

**Comment by connium** [comment]
> the spec was initially length 65, and was changed after adoption

Thanks for sharing this information. I wasn't aware of this fact.

> are [there] any other oddities like this I should be aware of?

I'm sorry, I cannot answer you this question. Well there are some other models that use a pad register to fill up to an even length (I don't know the exact model ids - you'll  have to look for `pad`).
Up to now I haven't encountered any issues.
