### ISSUE TITLE
Model 704/705 Reactive power control priority enumeration confusion

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#221]
The reactive power priority enumerations IEEE_1547 and PF are creating confusion.

The active/reactive power priority behavior specified in IEEE 1547-2018 is reactive power priority. It is most clear if the REACTIVE enumeration is used for setting the 1547 power priority.

The behavior of the PF enumeration for power priority is not clear. It does not seem like this would be a valid choice for a reactive power control other the power factor control. If reactive power control is desired as power factor, the power factor control should be used.

Based on the confusion surrounding these two enumerations, it is desirable to remove them from models 704 and 705 for the power priority points. The benefits of removing them now seem to outweigh the problems associated with another change. The value of the enumeration for VENDOR would be changed to 3.

Does anyone object to this change?

**Comment by bobfox** [comment]
Sorry, VENDOR would be changed to 2. So there would be three enumeration values: ACTIVE (0), REACTIVE (1), and VENDOR (2).

**Comment by FW22** [comment]
It's a good idea to clarify this. I would even go one step futher: The only priority that has a positive effect on the grid is REACTIVE. Our experience is, that ACTIVE power priority can even lead to oscillations - which is the opposite of grid support. E..g. SMA only supports REACTIVE power priority.
Why don't you remove this enumeration and make REACTIVE as the default until someone comes up with a real world use case for other modes of prioritization?

**Comment by bobfox** [comment]
For better or worse, it appears that active power priority is supported by some manufacturers in some cases so I don't think it can be removed.

There have been no objections to the initial proposal so we are going to move forward with it.
