### ISSUE TITLE
700 series model in sunspec model definition (smdx)

### ISSUE THREAD

**Issue by gustavowd** [sunspec/models#223]
Hi,

Why do not exist 700 series models in smdx format? Any reason fot that?

Best regards,
Gustavo

**Comment by jsbosch** [comment]
The new Dashboard uses JSON model definition files. I'm pretty sure the old Dashboard can't work with 700 level models. But if you need SMDX for your own software, the new Dashboard should be able to convert the JSON to SMDX for you.

**Comment by bobfox** [comment]
Some of the 700 series models contain SunSpec modeling extensions such as multiple repeating groups and nested repeating groups. These extension were not added to SMDX so many of the 7xx models can not be represented using the current SMDX modeling. Hopefully, it is not too difficult to move forward with the JSON model encoding.

**Comment by gustavowd** [comment]
Thanks for the explanation about 700 series models on smdx @bobfox  @jsbosch. Unfortunately, we have a backend / daemon that is completely dependent on smdx models, because it was developed with a improved version of the libsunspec library, which is available on github. For now i started to convert some of the 700 series models to sdmx in order to use with our inverters. For now I've only converted the 701 model and validated it with the xsd file (xml schema). In the future we will try to migrate the libsunspec to the json models.

Best regards,
Gustavo
