### ISSUE TITLE
Model 704 - Add VA_MAX_PCT to VarSetMod

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#224]
Add VA_MAX_PCT to VarSetMod to be consistent with other functions with these enumerations. Set VA_MAX_PCT value to 3 and VARS to 4,

**Comment by FW22** [comment]
@bobfox , could you please specify the effect of this change proposal to the complete enumerations for 704-VArSetMod, 705-DeptRef and 712-DeptRef? I hope they will be the same, after this change?

**Comment by bobfox** [comment]
After the change, for models 704, 705, and 712:

W_MAX_PCT = 0
VAR_MAX_PCT = 1
VAR_AVAIL_PCT = 2
VA_MAX_PCT = 3

For model 704, VarSetMod has an additional enumeration to allow vars as the unit:

VARS = 4

If VarSetMod is set to 0-3, VarSetPct is used for the setpoint in percent. If VarSetMod is set to 4, VarSet is used as the setpoint in vars.
