### ISSUE TITLE
Using model from id range 64900 as a placeholder to keep adresses stable

### ISSUE THREAD

**Issue by FW22** [sunspec/models#226]
Hi @bobfox ,
some of our customers rely upon static adresses of modbus registers. I'm aware that this is not SunSpec compliant and an initial model scan should be used instead to determine the adresses dynamically. Nevertheless we would like to keep existing applications working.

Therefore we would like to integrate a model from the id range 64900 (experimental use) as a placeholder between model 123 and model 160. This model would have a length that allows us to keep the same adresses for model 160.

I expect SunSpec dashboard to skip models in the 64900 range. Could you please confirm that?

Would this approach be SunSpec compliant?

**Comment by bobfox** [comment]
I am not sure I completely understand. Would the length of the model between 123 and 160 change over time or is it a one time adjustment?

The dashboard will ignore any models for which it is does not have the associated model definition.

If it is a one time adjustment, I don't think there are any issues with it. I think it would probably be better to get a set of extended model IDs assigned to you so there is no confusion about the context and meaning of the extended model. You can reserve them in blocks of 10 models by just sending a request to support@sunspec.org.

**Comment by FW22** [comment]
The length would be a one time adjustment. The idea to reserve a set of extended model ids is good, I'll think about it. But most importantly we don't break something with our appoach. Thank you for your quick response!
