### ISSUE TITLE
Kostal quirk - model chain terminated by single 0x0000?

### ISSUE THREAD

**Issue by andig** [sunspec/models#44]
Not a bug in the models presumable, but I'd appreciate help. I'm using gosunspec to walk the model chain on a Kostal grid inverter. Trying to read the next model id + length (2 words) after 802, instead of returning 0xFFFF 0xXXXX, I get a modbus 131 error.

If I instead read 1 word (model id) I get 0x0000 (instead of model id 0xFFFF).

What is the right way to check for end of model chain?

**Comment by altendky** [comment]
https://sunspec.org/wp-content/uploads/2015/06/SunSpec-Information-Models-12041.pdf
> End Model
> The Device Definition is terminated by a Model with ID ((0xFFFF)), follow by a length (L) value of zero.

**Comment by altendky** [comment]
@andig, have you made an account to get access to the documents?  As I recall the accounts are free etc.

**Comment by andig** [comment]
> have you made an account to get access to the documents? As I recall the accounts are free etc.

Got it now, thank you! Is there a good place (outside of this repo) to exchange information about implementation quirks? Looks like I might have hit one?

**Comment by altendky** [comment]
I thought there was a forum section on the website but I don't see it right now.  I don't recall it being particularly active.  So basically, no, I don't know of one.  This (and https://github.com/sunspec/models) are the only two places I have gone for any public activity.

Maybe just check with Kostal directly?

**Comment by cfstras** [comment]
one very helpful resource in debugging device issue is the suns.py: https://github.com/sunspec/pysunspec/blob/master/scripts/suns.py

When creating the SunspecClientDevice (l.71), you can pass a trace function which will receive all packets sent and received as a string. this way, you can see exactly what requests should work and compare with your implementation.

**Comment by andig** [comment]
Here is what happens:

````
2019/08/01 22:28:37 modbus: send 00 01 00 00 00 06 47 03 9c 40 00 02
2019/08/01 22:28:37 modbus: recv 00 01 00 00 00 07 47 03 04 53 75 6e 53
2019/08/01 22:28:37 modbus: send 00 02 00 00 00 06 47 03 9c 42 00 02
2019/08/01 22:28:38 modbus: recv 00 02 00 00 00 07 47 03 04 00 01 00 42
2019/08/01 22:28:38 modbus: send 00 03 00 00 00 06 47 03 9c 86 00 02
2019/08/01 22:28:38 modbus: recv 00 03 00 00 00 07 47 03 04 00 67 00 32
2019/08/01 22:28:38 modbus: send 00 04 00 00 00 06 47 03 9c ba 00 02
2019/08/01 22:28:38 modbus: recv 00 04 00 00 00 07 47 03 04 00 71 00 3c
2019/08/01 22:28:38 modbus: send 00 05 00 00 00 06 47 03 9c f8 00 02
2019/08/01 22:28:38 modbus: recv 00 05 00 00 00 07 47 03 04 00 78 00 1a
2019/08/01 22:28:38 modbus: send 00 06 00 00 00 06 47 03 9d 14 00 02
2019/08/01 22:28:38 modbus: recv 00 06 00 00 00 07 47 03 04 00 7b 00 18
2019/08/01 22:28:38 modbus: send 00 07 00 00 00 06 47 03 9d 2e 00 02
2019/08/01 22:28:38 modbus: recv 00 07 00 00 00 07 47 03 04 00 a0 00 44
2019/08/01 22:28:38 modbus: send 00 08 00 00 00 06 47 03 9d 74 00 02
2019/08/01 22:28:38 modbus: recv 00 08 00 00 00 07 47 03 04 03 22 00 3e
2019/08/01 22:28:38 modbus: send 00 09 00 00 00 06 47 03 9d b4 00 02
2019/08/01 22:28:38 modbus: recv 00 09 00 00 00 03 47 83 02
````

After the last model, it's no longer possible to read 2 words. I'll need to double-check if there's anything broken in last model definition (802) or if its bad implementation on the Kostal.

**Comment by nielsbasjes** [comment]
Looking at your problem description and this documentation by Kostal https://www.photovoltaikforum.com/core/attachment/81082-ba-kostal-interface-modbus-tcp-sunspec-pdf/ I found it seems to me that Kostal apparently does not conform 100% to Sunspec.
In SunSpec the end of the list marker is clearly defined, yet your Kostal device does something slightly different.

P.S. Yesterday I made the code I created to read data using SunSpec available on github.
https://github.com/nielsbasjes/energy
I've added a test case to simulate the effect you are seeing.
My code reads the Model header 1 register at a time so this code "should work" on your device too.

I've been running this at home reading the data from my SMA SunnyBoy 3.6 and on that device it works fine.

**Comment by andig** [comment]
> I found it seems to me that Kostal apparently does not conform 100% to Sunspec.
In SunSpec the end of the list marker is clearly defined, yet your Kostal device does something slightly different.

Right. Kostal has more or lessed confirmed this to be a bug via support. I'll close this issue as no longer a topic here.

> P.S. Yesterday I made the code I created to read data using SunSpec available on github.
https://github.com/nielsbasjes/energy

Interesting. I have for some time been developing https://github.com/volkszaehler/mbmd - different language, different goals. 

One thing that I see as common denominator is the mapping of specific registers (especially outside of sunspec) to a) their physical meaning and b) the necessary en/decoding. If you which we could join forces and design some kind of meta representation that would allow to create the likes of https://github.com/volkszaehler/mbmd/tree/master/meters/rs485 in a generative way.
