### ISSUE TITLE
Updated modeling and model encoding

### ISSUE THREAD

**Issue by bobfox** [sunspec/models#53]
All,

I just wanted to give you a heads up that SunSpec is about to release a draft of some modeling extensions and propose moving from xml to json for the model definition encoding. I wanted to let you know as it seems like there is some work being considered based on the current model definitions and the smdx encoding.  I would invite everyone to participate in evaluating the new specifications and providing comments. The draft spec should be available shortly and I will post the location to this issue. The modeling extensions are backward compatible and the plan is to migrate the existing models to the json encoding.

**Comment by andig** [comment]
It would be great to fix the outstanding issues before doing so or continue to support the xml models. Hopefully the cost is low if conversion is automatic. Doing so would help those of us that are stuck on existing tooling to benefit from the fixes.

**Comment by bobfox** [comment]
Yes, we will fix all the outstanding issues and continue to support the xml version of the models. The conversion can be made automatic if we update the xml definitions with the appropriate metadata in the model definitions. I think the best approach would probably be to always create the json version of the existing xml model definitions programatically and preform any updates in the xml version and then regenerate.

**Comment by nielsbasjes** [comment]
XML and Json are just carriers of the actual content.
If people think having the specs as json then I propose adding an XML to Json generator to this project. That way there is only 1 definition (in XML) that is available in multiple forms.
Using this adding an additional format (like Yaml) is then a trivial addition.

Additional: I'm working on software that depends on these definitions. Having actual releases (i.e. git tags) would really help in making my code a more reliable build.

**Comment by bobfox** [comment]
The drafts for updated modeling are available for review at https://sunspec.org/new-technology-for-review/. Please take a look and provide any feedback you might have. Also a SunSpec Modbus work group will be starting to discuss issues with the draft content. More information will be available shortly on sunspec.org.
