### ISSUE TITLE
Models Repo License Re: Private Copy and Modify Permission

### ISSUE THREAD

**Issue by 780Farva** [sunspec/models#66]
I've working with a third-party device that mostly adheres to Sunspec, but it has some incompatibilities that make reading it with the standard smdx files through tools like pysunspec unworkable. Since I can't force them to prioritize updating their firmware (I can only politely request, then wait and hope), my best work-around would be to duplicate this repo and add a branch wherein I edit the smdx files to match their map. That duplicate would, of course, be private.

However, since this repo doesn't have any explicit license the official GitHub "no-license" license is too restrictive for me to legally do that. So my question is two-fold:

1) Can I have permission from the copyright owners of this repo to make a private copy and modify smdx files?

and

2) Would the owner of this repo be open to including a license file? This will help people in situations like mine discover their options more quickly.

**Comment by bobfox** [comment]
In general, this seems like it could cause a lot of confusion. Having alternate versions of standardized model definitions that use the same model id seems like a bad idea. I have a couple of questions:

Am I understanding your request correctly?
What is the motivation for having model definition files for the alternate implementation? Typically the model definition files are used by tools wanting to process models in a general way. It seems like have these conflicting definition files would cause problems for any tool trying to interpret those models.

**Comment by altendky** [comment]
If a device is SunSpec-like but doesn't actually quite correctly follow SunSpec then having a copy of the models that have been modified to match the device seems useful.  That way any SunSpec xml reading tool can be given the modified xml files and talk to the device.

But sure, compliance would be preferred.  We aren't always in control of that though.

Regardless, the lack of a license file does seem like a bad thing.  Though I don't know my way around licensing data as opposed to source code.

**Comment by bobfox** [comment]
My primary concern is if the alternate definitions somehow start getting propagated. This would cause a lot of problems. Currently, the model id is really the only indicator a model definition user has to differentiate them. If the same model id is used for two different definitions, it is not possible to identify the standard version versus alternate versions. What if this pattern was repeated by multiple implementers all with their own custom version? It doesn't seem good. Historically, SunSpec has been pretty flexible in trying support vendors that may not be able to fully comply but creating alternate model definitions for the standard models seem like it may be a step too far.

**Comment by altendky** [comment]
This is a user attempting to deal with a vendor that isn't resolving the issue...  it is fact, reality, not a matter of preference.  It sounds like you are erring on the side of a license that bans modification?  I don't know if that's legally possible or not but...  nobody is encouraging deviations as a good thing here.  Just reality.

**Comment by 780Farva** [comment]
I think @altendky nailed it. I can't control whether this vendor adheres to sunspec perfectly, but I can control whether I make progress toward integrating my with them.

My plan is to hold these modified xml files very close to the vest. I want to take them into the closed-source world since having them propagate wouldn't be desirable at all. 

Because this repo doesn't have an explicit license file, github's terms of use default the license for the repo to be completely non-permissive. Details on the default license are [here](https://choosealicense.com/no-permission/). This is why I'm asking for explicit permission to make a closed-source copy of this repository so I can realize the changes I need to support this one-off case.

**Comment by bobfox** [comment]
We have updated the license and I think it provides what you need. I would rather see a different mechanism than changing the base model definition to address your issue but if you do go with that solution, I would request that you please try to manage it carefully.

**Comment by 780Farva** [comment]
@bobfox thank you very much for your help with this. The Apache 2 license is very workable for my needs.

I'll keep the modified files under lock and key, and I'll be encouraging the device vendor I mentioned to update to full compliance.
